// AUTO-GENERATED by scripts/generate-bg-presets.mjs — do not hand-edit.
// Re-run `bun scripts/generate-bg-presets.mjs` after changing PRESETS there;
// this file and public/bg-presets/*.png regenerate together, byte-identical
// on every re-run (deterministic renderer, no Math.random/Date.now in the
// pixel math). Each entry's palette/focus/luminance/safeSide came from
// running the real analyzeBackground() against the generated pixels — not
// hand-typed — so bundled presets and user-imported themes share one
// analysis path. `file` is a public/ root path (served over app://), not a
// bgasset:// URL — presets aren't user files.
import type { BackgroundThemeMeta } from '@desktop-shared/ipc-channels'

export const BACKGROUND_PRESETS: readonly BackgroundThemeMeta[] = [
  {
    version: 1,
    id: "preset-dawn",
    name: "晨曦",
    file: "/bg-presets/preset-dawn.png",
    width: 1920,
    height: 1200,
    luminance: 0.8481,
    focus: { x: 0.64, y: 0.4952 },
    safeSide: "left",
    palette: {
      accent: "#f6caa8",
      secondary: "#e57975",
      highlight: "#e5cd58"
    },
    createdAt: 0
  },
  {
    version: 1,
    id: "preset-deep",
    name: "深夜",
    file: "/bg-presets/preset-deep.png",
    width: 1920,
    height: 1200,
    luminance: 0.131,
    focus: { x: 0.36, y: 0.5442 },
    safeSide: "right",
    palette: {
      accent: "#233968",
      secondary: "#2f6174",
      highlight: "#2d2867"
    },
    createdAt: 0
  },
  {
    version: 1,
    id: "preset-moss",
    name: "苔痕",
    file: "/bg-presets/preset-moss.png",
    width: 1920,
    height: 1200,
    luminance: 0.3194,
    focus: { x: 0.36, y: 0.4613 },
    safeSide: "right",
    palette: {
      accent: "#28382a",
      secondary: "#4c5d46",
      highlight: "#3d5248"
    },
    createdAt: 0
  },
  {
    version: 1,
    id: "preset-slate",
    name: "灰蓝",
    file: "/bg-presets/preset-slate.png",
    width: 1920,
    height: 1200,
    luminance: 0.4221,
    focus: { x: 0.64, y: 0.4846 },
    safeSide: "left",
    palette: {
      accent: "#636d79",
      secondary: "#647578",
      highlight: "#646578"
    },
    createdAt: 0
  }
] as const
