/**
 * Playful present-participle verbs that the "thinking" spinner cycles
 * between turns. Ported verbatim from the fusion-code CLI
 * (`free-code/src/constants/spinnerVerbs.ts`) so the desktop UI reads
 * as a direct visual dialect of the terminal experience.
 *
 * One verb is sampled per assistant turn and kept stable for the whole
 * response — rotating it every frame would read as jittery. See
 * `stores/chat.ts → startAssistantMessage` for the sampling point.
 */
export const SPINNER_VERBS: readonly string[] = [
  'Accomplishing',
  'Actioning',
  'Actualizing',
  'Architecting',
  'Baking',
  'Beaming',
  "Beboppin'",
  'Befuddling',
  'Billowing',
  'Blanching',
  'Bloviating',
  'Boogieing',
  'Boondoggling',
  'Booping',
  'Bootstrapping',
  'Brewing',
  'Bunning',
  'Burrowing',
  'Calculating',
  'Canoodling',
  'Caramelizing',
  'Cascading',
  'Catapulting',
  'Cerebrating',
  'Channeling',
  'Channelling',
  'Choreographing',
  'Churning',
  'Clauding',
  'Coalescing',
  'Cogitating',
  'Combobulating',
  'Composing',
  'Computing',
  'Concocting',
  'Considering',
  'Contemplating',
  'Cooking',
  'Crafting',
  'Creating',
  'Crunching',
  'Crystallizing',
  'Cultivating',
  'Deciphering',
  'Deliberating',
  'Determining',
  'Dilly-dallying',
  'Discombobulating',
  'Doing',
  'Doodling',
  'Drizzling',
  'Ebbing',
  'Effecting',
  'Elucidating',
  'Embellishing',
  'Enchanting',
  'Envisioning',
  'Evaporating',
  'Fermenting',
  'Fiddle-faddling',
  'Finagling',
  'Flambéing',
  'Flibbertigibbeting',
  'Flowing',
  'Flummoxing',
  'Fluttering',
  'Forging',
  'Forming',
  'Frolicking',
  'Frosting',
  'Gallivanting',
  'Galloping',
  'Garnishing',
  'Generating',
  'Gesticulating',
  'Germinating',
  'Gitifying',
  'Grooving',
  'Gusting',
  'Harmonizing',
  'Hashing',
  'Hatching',
  'Herding',
  'Honking',
  'Hullaballooing',
  'Hyperspacing',
  'Ideating',
  'Imagining',
  'Improvising',
  'Incubating',
  'Inferring',
  'Infusing',
  'Ionizing',
  'Jitterbugging',
  'Julienning',
  'Kneading',
  'Leavening',
  'Levitating',
  'Lollygagging',
  'Manifesting',
  'Marinating',
  'Meandering',
  'Metamorphosing',
  'Misting',
  'Moonwalking',
  'Moseying',
  'Mulling',
  'Mustering',
  'Musing',
  'Nebulizing',
  'Nesting',
  'Newspapering',
  'Noodling',
  'Nucleating',
  'Orbiting',
  'Orchestrating',
  'Osmosing',
  'Perambulating',
  'Percolating',
  'Perusing',
  'Philosophising',
  'Photosynthesizing',
  'Pollinating',
  'Pondering',
  'Pontificating',
  'Pouncing',
  'Precipitating',
  'Prestidigitating',
  'Processing',
  'Proofing',
  'Propagating',
  'Puttering',
  'Puzzling',
  'Quantumizing',
  'Razzle-dazzling',
  'Razzmatazzing',
  'Recombobulating',
  'Reticulating',
  'Roosting',
  'Ruminating',
  'Sautéing',
  'Scampering',
  'Schlepping',
  'Scurrying',
  'Seasoning',
  'Shenaniganing',
  'Shimmying',
  'Simmering',
  'Skedaddling',
  'Sketching',
  'Slithering',
  'Smooshing',
  'Sock-hopping',
  'Spelunking',
  'Spinning',
  'Sprouting',
  'Stewing',
  'Sublimating',
  'Swirling',
  'Swooping',
  'Symbioting',
  'Synthesizing',
  'Tempering',
  'Thinking',
  'Thundering',
  'Tinkering',
  'Tomfoolering',
  'Topsy-turvying',
  'Transfiguring',
  'Transmuting',
  'Twisting',
  'Undulating',
  'Unfurling',
  'Unravelling',
  'Vibing',
  'Waddling',
  'Wandering',
  'Warping',
  'Whatchamacalliting',
  'Whirlpooling',
  'Whirring',
  'Whisking',
  'Wibbling',
  'Working',
  'Wrangling',
  'Zesting',
  'Zigzagging'
]

/** Pick a random verb — used once per assistant turn. */
export function sampleSpinnerVerb(): string {
  return SPINNER_VERBS[Math.floor(Math.random() * SPINNER_VERBS.length)]!
}

/**
 * 中文动词表 — 与英文表同样的俏皮劲儿（既有「琢磨中」这类正经进行时，
 * 也有「掐指一算」这类彩蛋），供中文界面下的思考行使用。
 */
export const SPINNER_VERBS_ZH: readonly string[] = [
  '琢磨中',
  '推敲中',
  '酝酿中',
  '思忖中',
  '盘算中',
  '梳理中',
  '编织中',
  '烹制中',
  '熬煮中',
  '搅拌中',
  '发酵中',
  '打磨中',
  '雕琢中',
  '拼装中',
  '搭建中',
  '排布中',
  '斟酌中',
  '掐指一算',
  '翻箱倒柜',
  '穿针引线',
  '添砖加瓦',
  '运筹帷幄',
  '苦思冥想',
  '灵光乍现',
  '奋笔疾书',
  '抽丝剥茧',
  '融会贯通',
  '按图索骥'
]

/**
 * Deterministically map the turn's sampled ENGLISH verb onto the Chinese
 * list. The store keeps sampling English (turnVerb is set once per turn in
 * startAssistantMessage, far from any i18n context); the RENDER layer picks
 * the display language. Hashing the English verb — instead of re-sampling —
 * keeps the Chinese verb stable for the whole turn and avoids threading the
 * lang through the store.
 */
export function zhSpinnerVerb(enVerb: string): string {
  let h = 0
  for (let i = 0; i < enVerb.length; i++) h = (h * 31 + enVerb.charCodeAt(i)) | 0
  return SPINNER_VERBS_ZH[Math.abs(h) % SPINNER_VERBS_ZH.length]!
}
