/**
 * Playful present-participle verbs that the "thinking" spinner cycles
 * between turns. Ported verbatim from the fusion-code CLI
 * (`free-code/src/constants/spinnerVerbs.ts`) so the desktop UI reads
 * as a direct visual dialect of the terminal experience.
 *
 * One verb is sampled per assistant turn and kept stable for the whole
 * response — rotating it every frame would read as jittery. See
 * `stores/chat.ts → startAssistantMessage` for the sampling point.
 */
export const SPINNER_VERBS: readonly string[] = [
  'Accomplishing',
  'Actioning',
  'Actualizing',
  'Architecting',
  'Baking',
  'Beaming',
  "Beboppin'",
  'Befuddling',
  'Billowing',
  'Blanching',
  'Bloviating',
  'Boogieing',
  'Boondoggling',
  'Booping',
  'Bootstrapping',
  'Brewing',
  'Bunning',
  'Burrowing',
  'Calculating',
  'Canoodling',
  'Caramelizing',
  'Cascading',
  'Catapulting',
  'Cerebrating',
  'Channeling',
  'Channelling',
  'Choreographing',
  'Churning',
  'Clauding',
  'Coalescing',
  'Cogitating',
  'Combobulating',
  'Composing',
  'Computing',
  'Concocting',
  'Considering',
  'Contemplating',
  'Cooking',
  'Crafting',
  'Creating',
  'Crunching',
  'Crystallizing',
  'Cultivating',
  'Deciphering',
  'Deliberating',
  'Determining',
  'Dilly-dallying',
  'Discombobulating',
  'Doing',
  'Doodling',
  'Drizzling',
  'Ebbing',
  'Effecting',
  'Elucidating',
  'Embellishing',
  'Enchanting',
  'Envisioning',
  'Evaporating',
  'Fermenting',
  'Fiddle-faddling',
  'Finagling',
  'Flambéing',
  'Flibbertigibbeting',
  'Flowing',
  'Flummoxing',
  'Fluttering',
  'Forging',
  'Forming',
  'Frolicking',
  'Frosting',
  'Gallivanting',
  'Galloping',
  'Garnishing',
  'Generating',
  'Gesticulating',
  'Germinating',
  'Gitifying',
  'Grooving',
  'Gusting',
  'Harmonizing',
  'Hashing',
  'Hatching',
  'Herding',
  'Honking',
  'Hullaballooing',
  'Hyperspacing',
  'Ideating',
  'Imagining',
  'Improvising',
  'Incubating',
  'Inferring',
  'Infusing',
  'Ionizing',
  'Jitterbugging',
  'Julienning',
  'Kneading',
  'Leavening',
  'Levitating',
  'Lollygagging',
  'Manifesting',
  'Marinating',
  'Meandering',
  'Metamorphosing',
  'Misting',
  'Moonwalking',
  'Moseying',
  'Mulling',
  'Mustering',
  'Musing',
  'Nebulizing',
  'Nesting',
  'Newspapering',
  'Noodling',
  'Nucleating',
  'Orbiting',
  'Orchestrating',
  'Osmosing',
  'Perambulating',
  'Percolating',
  'Perusing',
  'Philosophising',
  'Photosynthesizing',
  'Pollinating',
  'Pondering',
  'Pontificating',
  'Pouncing',
  'Precipitating',
  'Prestidigitating',
  'Processing',
  'Proofing',
  'Propagating',
  'Puttering',
  'Puzzling',
  'Quantumizing',
  'Razzle-dazzling',
  'Razzmatazzing',
  'Recombobulating',
  'Reticulating',
  'Roosting',
  'Ruminating',
  'Sautéing',
  'Scampering',
  'Schlepping',
  'Scurrying',
  'Seasoning',
  'Shenaniganing',
  'Shimmying',
  'Simmering',
  'Skedaddling',
  'Sketching',
  'Slithering',
  'Smooshing',
  'Sock-hopping',
  'Spelunking',
  'Spinning',
  'Sprouting',
  'Stewing',
  'Sublimating',
  'Swirling',
  'Swooping',
  'Symbioting',
  'Synthesizing',
  'Tempering',
  'Thinking',
  'Thundering',
  'Tinkering',
  'Tomfoolering',
  'Topsy-turvying',
  'Transfiguring',
  'Transmuting',
  'Twisting',
  'Undulating',
  'Unfurling',
  'Unravelling',
  'Vibing',
  'Waddling',
  'Wandering',
  'Warping',
  'Whatchamacalliting',
  'Whirlpooling',
  'Whirring',
  'Whisking',
  'Wibbling',
  'Working',
  'Wrangling',
  'Zesting',
  'Zigzagging'
]

/** Pick a random verb — used once per assistant turn. */
export function sampleSpinnerVerb(): string {
  return SPINNER_VERBS[Math.floor(Math.random() * SPINNER_VERBS.length)]!
}

/**
 * 中文动词表 — 全部用大白话，普通用户一眼看懂 AI 正在干什么。第一版
 * 移植了英文表的俏皮劲儿（掐指一算 / 抽丝剥茧 / 按图索骥…），但文艺
 * 成语对非技术用户是理解成本而不是彩蛋——直白比有趣优先。统一
 * 「XX中」的口语节奏，读起来是「正在做事」，不是在猜谜。
 */
export const SPINNER_VERBS_ZH: readonly string[] = [
  '思考中',
  '分析中',
  '构思中',
  '推理中',
  '规划中',
  '整理中',
  '归纳中',
  '汇总中',
  '总结中',
  '处理中',
  '计算中',
  '准备中',
  '编写中',
  '生成中',
  '核对中',
  '检查中',
  '复查中',
  '筛选中',
  '比对中',
  '润色中',
  '查资料中',
  '找答案中',
  '想办法中',
  '打草稿中',
  '列要点中',
  '理思路中',
  '拆解问题中',
  '组织语言中'
]

/**
 * Deterministically map the turn's sampled ENGLISH verb onto the Chinese
 * list. The store keeps sampling English (turnVerb is set once per turn in
 * startAssistantMessage, far from any i18n context); the RENDER layer picks
 * the display language. Hashing the English verb — instead of re-sampling —
 * keeps the Chinese verb stable for the whole turn and avoids threading the
 * lang through the store.
 */
export function zhSpinnerVerb(enVerb: string): string {
  let h = 0
  for (let i = 0; i < enVerb.length; i++) h = (h * 31 + enVerb.charCodeAt(i)) | 0
  return SPINNER_VERBS_ZH[Math.abs(h) % SPINNER_VERBS_ZH.length]!
}
